// tools/soundscapes.mjs
// Soundscape Presets and Sound Design Archetypes for all 7 video formats.
// Maps each style to its signature BGM, default volumes, and primary SFX palette.

export const SFX_CATALOG = {
  whoosh: {
    id: "whoosh",
    name: "Cinematic Whoosh",
    icon: "💨",
    category: "transition",
    file: "whoosh.mp3",
    duration: 1.75,
    defaultVolume: 0.45,
    description: "Lướt cảnh, đổi góc máy, chuyển hồi dứt khoát",
  },
  pop: {
    id: "pop",
    name: "Pop Bubble",
    icon: "🫧",
    category: "accent",
    file: "pop.mp3",
    duration: 0.48,
    defaultVolume: 0.55,
    description: "Sticker nảy, tag hiện, nhãn nổi bật",
  },
  ding: {
    id: "ding",
    name: "Insight Bell Ding",
    icon: "🔔",
    category: "accent",
    file: "ding.mp3",
    duration: 1.30,
    defaultVolume: 0.5,
    description: "Quy tắc vàng, lời khuyên cốt lõi, điểm mấu chốt",
  },
  click: {
    id: "click",
    name: "UI Tap Click",
    icon: "🖱️",
    category: "accent",
    file: "click.mp3",
    duration: 1.04,
    defaultVolume: 0.55,
    description: "Nhấp chuột, chạm phím, chi tiết nhỏ xuất hiện",
  },
  chime: {
    id: "chime",
    name: "Victory Payoff Chime",
    icon: "✨",
    category: "payoff",
    file: "chime.mp3",
    duration: 2.0,
    defaultVolume: 0.6,
    description: "Kết luận chiến thắng, lời giải mở nút thắt",
  },
  deep_boom: {
    id: "deep_boom",
    name: "Deep Cinematic Boom",
    icon: "💥",
    category: "impact",
    file: "deep_boom.mp3",
    duration: 2.93,
    defaultVolume: 0.55,
    description: "Cú sốc mở đầu, phá sản, thảm họa, biến cố lớn",
  },
  sub_drop: {
    id: "sub_drop",
    name: "808 Sub-Bass Drop",
    icon: "🔊",
    category: "impact",
    file: "sub_drop.mp3",
    duration: 2.36,
    defaultVolume: 0.6,
    description: "Đột phá tư duy, punchline sắc bén, nhịp bass dội",
  },
  camera_shutter: {
    id: "camera_shutter",
    name: "DSLR Camera Shutter",
    icon: "📸",
    category: "evidence",
    file: "camera_shutter.mp3",
    duration: 0.15,
    defaultVolume: 0.65,
    description: "Hồ sơ mật, ảnh hiện trường, bằng chứng hé lộ",
  },
  typewriter: {
    id: "typewriter",
    name: "Mechanical Typewriter",
    icon: "⌨️",
    category: "evidence",
    file: "typewriter.mp3",
    duration: 0.08,
    defaultVolume: 0.55,
    description: "Gõ máy đánh chữ, ghi chép điều tra, terminal",
  },
  heartbeat: {
    id: "heartbeat",
    name: "Visceral Heartbeat",
    icon: "💓",
    category: "tension",
    file: "heartbeat.mp3",
    duration: 0.36,
    defaultVolume: 0.7,
    description: "Nín thở, nhịp tim căng thẳng trước ngưỡng tử",
  },
  alarm: {
    id: "alarm",
    name: "Hazard Warning Siren",
    icon: "🚨",
    category: "tension",
    file: "alarm.mp3",
    duration: 0.70,
    defaultVolume: 0.55,
    description: "Cảnh báo nguy hiểm, nhiễm xạ, khẩn cấp đỏ",
  },
  glitch: {
    id: "glitch",
    name: "Cyber Matrix Glitch",
    icon: "⚡",
    category: "impact",
    file: "glitch.mp3",
    duration: 0.40,
    defaultVolume: 0.55,
    description: "Gián đoạn tín hiệu số, bẫy dopamine, lỗi hệ thống",
  },
  cash_register: {
    id: "cash_register",
    name: "Cash Register Cha-ching",
    icon: "💰",
    category: "payoff",
    file: "cash_register.mp3",
    duration: 0.84,
    defaultVolume: 0.55,
    description: "Tỷ đô, lợi nhuận khổng lồ, bẫy tài chính",
  },
};

export const SOUNDSCAPE_PRESETS = {
  compare: {
    style: "compare",
    label: "So Sánh (Direct Clash)",
    defaultBgm: "monkeys-spinning",
    ambientVol: 0.14,
    boostVol: 0.28,
    primarySfx: ["whoosh", "pop", "ding", "click", "chime"],
    pacingMinGap: 2.0,
  },
  survival: {
    style: "survival",
    label: "Sinh Tồn (Survival Escalation)",
    defaultBgm: "volatile-reaction",
    ambientVol: 0.12,
    boostVol: 0.32,
    primarySfx: ["deep_boom", "heartbeat", "alarm", "whoosh", "sub_drop"],
    pacingMinGap: 1.8,
  },
  science: {
    style: "science",
    label: "Khoa Học (Science Discovery)",
    defaultBgm: "carefree",
    ambientVol: 0.15,
    boostVol: 0.28,
    primarySfx: ["pop", "ding", "whoosh", "click", "chime"],
    pacingMinGap: 2.2,
  },
  mystery: {
    style: "mystery",
    label: "Kỳ Án (Investigation & Mystery)",
    defaultBgm: "anxiety",
    ambientVol: 0.11,
    boostVol: 0.35,
    primarySfx: ["heartbeat", "deep_boom", "camera_shutter", "typewriter", "ding"],
    pacingMinGap: 1.6,
  },
  vox: {
    style: "vox",
    label: "Vox Collage (Creative Explainer)",
    defaultBgm: "sneaky-snitch",
    ambientVol: 0.12,
    boostVol: 0.28,
    primarySfx: ["pop", "camera_shutter", "cash_register", "whoosh", "ding"],
    pacingMinGap: 1.8,
  },
  newspaper: {
    style: "newspaper",
    label: "Retro Newspaper (Investigative Dossier)",
    defaultBgm: "anxiety",
    ambientVol: 0.11,
    boostVol: 0.34,
    primarySfx: ["typewriter", "camera_shutter", "deep_boom", "whoosh", "cash_register"],
    pacingMinGap: 1.6,
  },
  kinetic: {
    style: "kinetic",
    label: "Dark Cyber Kinetic (High-Impact Minimalist)",
    defaultBgm: "volatile-reaction",
    ambientVol: 0.12,
    boostVol: 0.32,
    primarySfx: ["sub_drop", "glitch", "whoosh", "click", "ding"],
    pacingMinGap: 1.5,
  },
};
