// Configuration, Tier styling, layout coordinates, and curated presets for Tier List Ranking Video Generator.
// Inspired by TikTok/Shorts viral tier list ranking videos (e.g. source_videos/Telegram Web.mp4).
// Format: 9:16 Vertical (1080x1920), Dark Grid Blueprint slate, 6 Tiers (SSS, S, A, B, C, D),
// dynamic candidate showcase, and physics slam placement into tier tray with SFX & camera shake.

export const TIER_DEFINITIONS = [
  {
    id: "SSS",
    name: "SSS",
    icon: "👑",
    label: "SIÊU PHẨM",
    labelEn: "MASTERPIECE",
    bgGradient: "linear-gradient(180deg, #d32f2f 0%, #b71c1c 100%)",
    borderColor: "#ff2a4b",
    glowColor: "rgba(255, 42, 75, 0.75)",
    textColor: "#ffffff",
    rowBg: "rgba(22, 14, 16, 0.92)",
    rankOrder: 1,
  },
  {
    id: "S",
    name: "S",
    icon: "⭐",
    label: "XUẤT SẮC",
    labelEn: "EXCELLENT",
    bgGradient: "linear-gradient(180deg, #e65100 0%, #bf360c 100%)",
    borderColor: "#ff6f1f",
    glowColor: "rgba(255, 111, 31, 0.7)",
    textColor: "#ffffff",
    rowBg: "rgba(24, 16, 12, 0.92)",
    rankOrder: 2,
  },
  {
    id: "A",
    name: "A",
    icon: "🥇",
    label: "RẤT TỐT",
    labelEn: "GREAT",
    bgGradient: "linear-gradient(180deg, #fbc02d 0%, #f57f17 100%)",
    borderColor: "#fbc02d",
    glowColor: "rgba(251, 192, 45, 0.7)",
    textColor: "#000000",
    rowBg: "rgba(24, 22, 12, 0.92)",
    rankOrder: 3,
  },
  {
    id: "B",
    name: "B",
    icon: "🥈",
    label: "KHÁ ỔN",
    labelEn: "DECENT",
    bgGradient: "linear-gradient(180deg, #546e7a 0%, #37474f 100%)",
    borderColor: "#90a4ae",
    glowColor: "rgba(144, 164, 174, 0.55)",
    textColor: "#ffffff",
    rowBg: "rgba(18, 22, 26, 0.92)",
    rankOrder: 4,
  },
  {
    id: "C",
    name: "C",
    icon: "🥉",
    label: "TRUNG BÌNH",
    labelEn: "AVERAGE",
    bgGradient: "linear-gradient(180deg, #2e7d32 0%, #1b5e20 100%)",
    borderColor: "#4caf50",
    glowColor: "rgba(76, 175, 80, 0.7)",
    textColor: "#ffffff",
    rowBg: "rgba(14, 24, 16, 0.92)",
    rankOrder: 5,
  },
  {
    id: "D",
    name: "D",
    icon: "📉",
    label: "KHÔNG NÊN THỬ",
    labelEn: "AVOID",
    bgGradient: "linear-gradient(180deg, #006064 0%, #004d40 100%)",
    borderColor: "#00e5ff",
    glowColor: "rgba(0, 229, 255, 0.7)",
    textColor: "#ffffff",
    rowBg: "rgba(12, 22, 25, 0.92)",
    rankOrder: 6,
  },
];


export const TIERLIST_LANG_META = {
  vi: {
    name: "Tiếng Việt",
    badge: "BẢNG XẾP HẠNG",
    eyebrow: "TIER LIST ĐẲNG CẤP",
    defaultVoice: "vi-VN-NamMinhNeural",
    watermark: "@ranking.vietnam",
    candidateTitle: "ỨNG VIÊN ĐANG ĐÁNH GIÁ",
    verdictTitle: "CHỐT BẬC:",
  },
  en: {
    name: "English (US)",
    badge: "OFFICIAL TIER LIST",
    eyebrow: "SSS TO D RANKING",
    defaultVoice: "en-US-AndrewNeural",
    watermark: "@tierlist.official",
    candidateTitle: "CURRENT CONTENDER",
    verdictTitle: "FINAL TIER:",
  },
  de: {
    name: "Deutsch",
    badge: "TIER LIST RANGLISTE",
    eyebrow: "SSS BIS D BEWERTUNG",
    defaultVoice: "de-DE-ConradNeural",
    watermark: "@tierlist.de",
    candidateTitle: "KANDIDAT IM TEST",
    verdictTitle: "PLATZIERUNG:",
  },
  fr: {
    name: "Français",
    badge: "CLASSEMENT TIER LIST",
    eyebrow: "DE SSS À D",
    defaultVoice: "fr-FR-HenriNeural",
    watermark: "@tierlist.fr",
    candidateTitle: "CANDIDAT EN COURS",
    verdictTitle: "RANG FINAL:",
  },
  ja: {
    name: "日本語",
    badge: "ティアリスト格付け",
    eyebrow: "SSSからDランク徹底格付け",
    defaultVoice: "ja-JP-KeitaNeural",
    watermark: "@tierlist.japan",
    candidateTitle: "現在審査中の候補",
    verdictTitle: "決定ランク:",
  },
  ko: {
    name: "한국어",
    badge: "티어 리스트 랭킹",
    eyebrow: "SSS부터 D까지 등급전",
    defaultVoice: "ko-KR-InJoonNeural",
    watermark: "@tierlist.korea",
    candidateTitle: "심사 중인 후보",
    verdictTitle: "최종 등급:",
  },
};

// Curated Tier List Topics
export const CURATED_TIERLIST_TOPICS = {
  "tierlist-idle-games-vi": {
    id: "idle-games-ranking",
    slug: "tierlist-idle-games-vi",
    lang: "vi",
    topicTitle: "XẾP HẠNG 5 TỰA GAME QUẢN LÝ TIỆM GÂY NGHIỆN",
    headline: "CON GAME NÀO XỨNG ĐÁNG BẬC SSS?",
    aspectRatio: "9:16",
    totalDuration: 65,
    items: [
      {
        id: "game-1",
        name: "Cooking Stickman",
        subtitle: "Quán Ăn Người Que",
        tier: "C",
        iconUrl: "assets/images/item-1-icon.jpg",
        mediaUrl: "assets/images/item-1-showcase.jpg",
        hook: "Mở đầu bảng xếp hạng là Cooking Stickman, tựa game làm bếp quen thuộc.",
        review: "Đồ họa người que hài hước, cày tiền rất sướng tay ở giai đoạn đầu, nhưng càng về sau quảng cáo xuất hiện khá dày đặc.",
        verdict: "Vì vậy, mình chỉ có thể xếp tựa game này vào bậc C!",
      },
      {
        id: "game-2",
        name: "Idle Supermarket",
        subtitle: "Đế Chế Siêu Thị 2D",
        tier: "B",
        iconUrl: "assets/images/item-2-icon.jpg",
        mediaUrl: "assets/images/item-2-showcase.jpg",
        hook: "Ứng viên số hai là Idle Supermarket Tycoon, siêu thị hoạt hình quen thuộc.",
        review: "Quản lý quầy hàng và bãi đỗ xe trực quan, hình ảnh tươi sáng, tuy nhiên lối chơi về sau hơi lặp lại.",
        verdict: "Một trải nghiệm khá tốt, xứng đáng dừng chân ở bậc B!",
      },
      {
        id: "game-3",
        name: "My Perfect Hotel",
        subtitle: "Khách Sạn 5 Sao",
        tier: "A",
        iconUrl: "assets/images/item-3-icon.jpg",
        mediaUrl: "assets/images/item-3-showcase.jpg",
        hook: "Vị trí thứ ba thuộc về My Perfect Hotel của SayGames.",
        review: "Mở khóa phòng, phục vụ khách, thuê nhân viên với nhịp độ dồn dập đến nghẹt thở. Cảm giác mở rộng từng tầng khách sạn vô cùng gây nghiện.",
        verdict: "Không còn nghi ngờ gì nữa, bậc A hoàn toàn thuyết phục!",
      },
      {
        id: "game-4",
        name: "Supermarket Sim",
        subtitle: "Mô Phỏng Siêu Thị 3D",
        tier: "S",
        iconUrl: "assets/images/item-4-icon.jpg",
        mediaUrl: "assets/images/item-4-showcase.jpg",
        hook: "Tiếp theo là cơn sốt Supermarket Simulator 3D góc nhìn thứ nhất.",
        review: "Tự tay bốc dỡ thùng hàng, quét mã vạch và thối tiền thừa cho khách cực kỳ chân thực, chơi cực kỳ thỏa mãn.",
        verdict: "Trải nghiệm nhập vai đỉnh cao, trao ngay tấm vé vào bậc S!",
      },
      {
        id: "game-5",
        name: "Monkey Mart",
        subtitle: "Siêu Thị Khỉ Chuối",
        tier: "SSS",
        iconUrl: "assets/images/item-5-icon.jpg",
        mediaUrl: "assets/images/item-5-showcase.jpg",
        hook: "Và trùm cuối bảng xếp hạng hôm nay không ai khác ngoài Monkey Mart!",
        review: "Chú khỉ thoăn thoắt trồng chuối, nuôi gà lấy trứng, phục vụ khách hàng siêu mượt mà không hề có độ trễ.",
        verdict: "Vương miện hoàng gia SSS chính thức thuộc về Monkey Mart!",
      },
    ],
  },
  "tierlist-fast-food-vi": {
    id: "fast-food-ranking",
    slug: "tierlist-fast-food-vi",
    lang: "vi",
    topicTitle: "XẾP HẠNG CÁC THƯƠNG HIỆU THỨC ĂN NHANH TẠI VIỆT NAM",
    headline: "AI LÀ ÔNG HOÀNG BẬC SSS?",
    aspectRatio: "9:16",
    totalDuration: 60,
    items: [
      {
        id: "ff-1",
        name: "Lotteria",
        subtitle: "Gà rán & Burger truyền thống",
        tier: "C",
        iconUrl: "assets/images/lotteria.jpg",
        mediaUrl: "assets/images/lotteria_showcase.jpg",
        hook: "Mở đầu là Lotteria, thương hiệu gắn liền với tuổi thơ nhiều thế hệ.",
        review: "Menu phong phú, giá thành vừa túi tiền học sinh sinh viên nhưng chất lượng món ăn gần đây không có nhiều bứt phá.",
        verdict: "Lotteria tạm thời an vị ở bậc C!",
      },
      {
        id: "ff-2",
        name: "KFC",
        subtitle: "Ông già gà rán đại chúng",
        tier: "B",
        iconUrl: "assets/images/kfc.jpg",
        mediaUrl: "assets/images/kfc_showcase.jpg",
        hook: "Tiếp theo là KFC, cái tên phổ biến nhất nhì thị trường.",
        review: "Công thức gà rán giòn rụm đậm đà, khoai tây ngon nhưng thỉnh thoảng gà bị khô dầu nếu để lâu.",
        verdict: "Vị trí bậc B xứng đáng cho KFC!",
      },
      {
        id: "ff-3",
        name: "McDonald's",
        subtitle: "Vua Burger & Khoai chiên",
        tier: "A",
        iconUrl: "assets/images/mcdonalds.jpg",
        mediaUrl: "assets/images/mcdonalds_showcase.jpg",
        hook: "Vị trí tiếp theo gọi tên McDonald's.",
        review: "Khoai tây chiên giòn đỉnh nóc kịch trần, burger bò chuẩn vị quốc tế và quầy kem Sundae ngon mê ly.",
        verdict: "McDonald's ẵm trọn bậc A chất lượng!",
      },
      {
        id: "ff-4",
        name: "Popeyes",
        subtitle: "Gà rán cay Louisiana",
        tier: "S",
        iconUrl: "assets/images/popeyes.jpg",
        mediaUrl: "assets/images/popeyes_showcase.jpg",
        hook: "Ứng viên bậc cao không thể thiếu gà cay Popeyes.",
        review: "Lớp vỏ bột tẩm ướp giòn tan vô đối, thịt bên trong mềm mọng ngập nước và bánh quy mật ong đỉnh cao.",
        verdict: "Xứng đáng bậc S điểm mười!",
      },
      {
        id: "ff-5",
        name: "Jollibee",
        subtitle: "Gà giòn vui vẻ & Mì Ý sốt bò bằm",
        tier: "SSS",
        iconUrl: "assets/images/jollibee.jpg",
        mediaUrl: "assets/images/jollibee_showcase.jpg",
        hook: "Và quán quân thống trị lòng người hâm mộ Việt Nam: Jollibee!",
        review: "Gà giòn rụm ngọt thịt hòa quyện cùng đĩa mì Ý sốt cà ri bò bằm thơm nức mũi, giá lại siêu hời cho mọi nhà.",
        verdict: "Bậc SSS vương miện tuyệt đối gọi tên Jollibee!",
      },
    ],
  },
};
